name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop 
  pull_request:
    branches:
      - main
      - develop

jobs:
  CI_tests:
    name: Deploy to Staging
    runs-on: ubuntu-22.04
    environment: staging
    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'

      - name: Install Dependencies
        run: npm install --force
        env:
           NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}
           NEXT_PUBLIC_PROD_URL: ${{ secrets.NEXT_PUBLIC_PROD_URL }}
           NEXT_PUBLIC_DEV_URL: ${{ secrets.NEXT_PUBLIC_DEV_URL }}
           NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
           NEXT_PUBLIC_REGISTER: ${{ secrets.NEXT_PUBLIC_REGISTER }}
           NEXT_PUBLIC_YEARLY_PLAN: ${{ secrets.NEXT_PUBLIC_YEARLY_PLAN }}
           NEXT_PUBLIC_MONTHLY_PLAN: ${{ secrets.NEXT_PUBLIC_MONTHLY_PLAN }}
           AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
           AUTH_URL: https://beta.modocaverna.com
           AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
           AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}

      - name: Lint Project
        run: npx eslint . --fix

      - name: Build Project
        run: npm run build
